### ISSUE TITLE
ImportError: cannot import name 'helpers' from 'utils' 

### ISSUE THREAD

**Issue by funeconomist** [daniegr/EfficientPose#10]
As the name of the issue says, i am having trouble running this. 

Googled around and saw this to resolve issue. https://github.com/omar-florez/scratch_mlp/issues/6
went to line 8

Changed

`from utils import helpers`

to 

`import utils`

worked but then code had issues when it came to running the helper. Can someone help?

would appreciate your help @daniegr

**Comment by daniegr** [comment]
@funeconomist: Which Python version are you running? Version 3.6.6 does the job for me. Alternatively you may check if `import utils.helpers as helpers` makes any difference.

**Comment by funeconomist** [comment]
@daniegr actually that made the world difference. Thanks for the tip. That resolved my problem
