### ISSUE TITLE
COCO

### ISSUE THREAD

**Issue by mcwoojcik** [daniegr/EfficientPose#11]
Hello,

Are you maybe going to train those networks on COCO dataset? Or maybe are you going to share instruction how can I do the training process to train it on COCO or another custom dataset? 

Thank you in advance for your answer :)

**Comment by daniegr** [comment]
@mcwoojcik: At the moment we are not planning to train our models on COCO, mainly as we focus our research on single-person applications, which are well facilitated by the [MPII dataset](http://human-pose.mpi-inf.mpg.de/). If you would like to extend the framework yourself for the multi-person setting, we are eager to get to know about your results. Details on the optimization process are available in our paper: [EfficientPose paper](https://arxiv.org/abs/2004.12186)

**Comment by mcwoojcik** [comment]
Thank you for very quick answer. I understand the dataset issue for single person. I will consider to provide training on COCO :)
