### ISSUE TITLE
Camera only exits out with "Q" when no extra paramters

### ISSUE THREAD

**Issue by funeconomist** [daniegr/EfficientPose#13]
@daniegr amazing package and code. This is truly one of the best packages on pose estimation I found. Everything is super clean and efficient. Truly a masterpiece. 

Noticed though that I can only exit out of the camera using "Q" when its just 
`python track.py` when I try using it with other models, the Q exit does not work and I have to terminate it from terminal. I don't know if you encountered that as well

**Comment by daniegr** [comment]
@funeconomist: Thanks man. Highly appreciated! Regarding your issue, didn't the program even quit if you clicked the camera screen before typing 'Q'?
