### ISSUE TITLE
Add efficientnet-lite models

### ISSUE THREAD

**Issue by ManuelPalermo** [daniegr/EfficientPose#16]
Hi @daniegr thank you for this great package!

Would you consider also adding the EfficientNet-lite versions? These were specifically created to replace some layers (eg. swish, SE) which don't run properly on some accelerators and are not properly supported by inference libraries(onnx, opencv-dnn), and offer better support for post-training quantization.

This addition would be really nice for people looking to run these models on edge devices.

**Comment by daniegr** [comment]
@ManuelPalermo: Great suggestion and very in line with our research activities. We have already carried out experiments for a Lite version of EfficientPose RT, and we are planning to launch this model here in the upcoming weeks.

**Comment by ManuelPalermo** [comment]
That's great to hear! Let me know when they are out so I close this issue

**Comment by daniegr** [comment]
@ManuelPalermo: Feel free to explore our EfficientPose Lite variants and please let me know if you have any further enquires.

**Comment by ManuelPalermo** [comment]
Thank you for the addition!
