### ISSUE TITLE
Running python track.py gives errors in new commit (Everything has broken)

### ISSUE THREAD

**Issue by duckduck-sys** [daniegr/EfficientPose#19]
Starting from a clean environment with python 3.6 and `pip install -r requirements.txt`, running 

`python track.py`

Gives the error:

```
Traceback (most recent call last):
  File "track.py", line 589, in <module>
    main(file_path=file_path, model_name=model_name, framework_name=framework_name, visualize=visualize, store=store)
  File "track.py", line 535, in main
    perform_tracking(video=True, file_path=None, model_name=model_name, framework_name=framework_name, visualize=False, store=store)
  File "track.py", line 496, in perform_tracking
    model, resolution = get_model(framework, model_variant)
  File "track.py", line 48, in get_model
    model = lite.Interpreter(model_path=join('models', 'tflite', 'EfficientPose{0}.tflite'.format(model_variant.upper())))
  File "/home/user/anaconda3/envs/EfficientPose/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter.py", line 206, in __init__
    model_path))
ValueError: Could not open 'models/tflite/EfficientPoseILITE.tflite'.
```

Which is just an error related to the name of the models. But changing the model name just gives a new error:

```
Traceback (most recent call last):
  File "track.py", line 589, in <module>
    main(file_path=file_path, model_name=model_name, framework_name=framework_name, visualize=visualize, store=store)
  File "track.py", line 535, in main
    perform_tracking(video=True, file_path=None, model_name=model_name, framework_name=framework_name, visualize=False, store=store)
  File "track.py", line 501, in perform_tracking
    coordinates = analyze(video, file_path, model, framework, resolution, lite)
  File "track.py", line 323, in analyze
    coordinates = analyze_camera(model, framework, resolution, lite)
  File "track.py", line 145, in analyze_camera
    frame_height, frame_width = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shap
```

Choosing other models also gives errors.. For example using keras:

`python track.py --framework=keras`

After fixing the model name error, it also gives errors:

```
Traceback (most recent call last):
  File "track.py", line 589, in <module>
    main(file_path=file_path, model_name=model_name, framework_name=framework_name, visualize=visualize, store=store)
  File "track.py", line 535, in main
    perform_tracking(video=True, file_path=None, model_name=model_name, framework_name=framework_name, visualize=False, store=store)
  File "track.py", line 496, in perform_tracking
    model, resolution = get_model(framework, model_variant)
  File "track.py", line 29, in get_model
    model = load_model(join('models', 'keras', 'EfficientPose{0}.h5'.format(model_variant.upper())), custom_objects={'BilinearWeights': helpers.keras_BilinearWeights, 'Swish': helpers.Swish(helpers.eswish), 'eswish': helpers.eswish, 'swish1': helpers.swish1})
  File "/home/user/anaconda3/envs/EfficientPose/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 143, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/user/anaconda3/envs/EfficientPose/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 160, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

I was trying out EfficientPose a few weeks ago and it worked fine. But with the recent commits everything seems broken.

**Comment by daniegr** [comment]
@duckduck-sys: I am sorry to hear that the recent changes caused troubles. I suspect that this is an issue that is not consistent across OS (probably due to differences in parsing of file paths), since the code still runs perfectly fine in a Mac environment. However, I would definitively look into this and try to come up with a stable solution. Regarding the other issues you mention, could you do me a favour in verifying that both of these errors still appear if you 1) reconnect the camera you are using (after fixing the path name issue) and if you 2) provide inputs in the form of a static image (using the path-argument) rather than the camera?

**Comment by duckduck-sys** [comment]
Hi @daniegr 

I'm using Ubuntu 18.04. Clean Python 3.6 environment with pip install requirements. Focusing on pose estimation on test image using

`python track.py --path=utils/MPII.jpg`

It seems that two things have broken:

**Naming**

If using TF and Lite model, get error:

`tensorflow.python.framework.errors_impl.NotFoundError: models/tensorflow/EfficientPoseILITE.pb; No such file or directory`

If using Keras and Lite model, get error:

`OSError: SavedModel file does not exist at: models/keras/EfficientPoseIILITE.h5/{saved_model.pbtxt|saved_model.pb}`

If using tflite and Lite model, get error:

`ValueError: Could not open 'models/tflite/EfficientPoseIILITE.tflite'.`

A quick and dirty fix for this is to just rename the Lite models in the model folders to LITE, then it runs. 
Using the non-Lite models works fine for Tensorflow, tflite and Pytorch, but all keras models fail, see below.

**Keras models**

For Keras, all models fail, neither regular or Lite models work. Running

`python track.py --path=utils/MPII.jpg --framework=keras --model=IV`

Returns

```
Traceback (most recent call last):
  File "track.py", line 589, in <module>
    main(file_path=file_path, model_name=model_name, framework_name=framework_name, visualize=visualize, store=store)
  File "track.py", line 543, in main
    perform_tracking(video=False, file_path=normpath(file_path), model_name=model_name, framework_name=framework_name, visualize=visualize, store=store)
  File "track.py", line 496, in perform_tracking
    model, resolution = get_model(framework, model_variant)
  File "track.py", line 29, in get_model
    model = load_model(join('models', 'keras', 'EfficientPose{0}.h5'.format(model_variant.upper())), custom_objects={'BilinearWeights': helpers.keras_BilinearWeights, 'Swish': helpers.Swish(helpers.eswish), 'eswish': helpers.eswish, 'swish1': helpers.swish1})
  File "/home/user/anaconda3/envs/EfficientPose/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 143, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/user/anaconda3/envs/EfficientPose/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 160, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

For me a simple fix was to install an older version of h5py.

`pip install h5py==2.10.0`

I suggest to either regenerate the Keras models with the [new h5py 3](https://pypi.org/project/h5py/#history), or put in h5py==2.10.0 in the requirement list to avoid this issue.
