### ISSUE TITLE
C/C++ core

### ISSUE THREAD

**Issue by ihmc3jn09hk** [daniegr/EfficientPose#21]
Hi @daniegr , EfficientPose looks promising on Single Human Pose estimation comparing with HRNet. Your statistics show somehow it can beat the current best, OpenPose, with a small model size. Would it be possible for you to provide a C/C++ version of the EfficientPose IV in PyTorch?

**Comment by daniegr** [comment]
@ihmc3jn09hk: Thank you for your comment and suggestion! I agree with you that it will be valuable to port the models to a C framework optimizing models for inference speed. We definitively have this aspect in mind, but we do not at the moment have the resources necessary to perform this task. If you are eager yourself to research into this or if you know about a procedure to achieve this conversion I would be glad to hear back from you. The models (except the Lite versions) are made available in PyTorch.

**Comment by ihmc3jn09hk** [comment]
@daniegr Thanks for your response. Will double check the performance against OpenPose before starting further investigation.
