### ISSUE TITLE
Skip Connections

### ISSUE THREAD

**Issue by AIGR-sw** [daniegr/EfficientPose#26]
@daniegr: Thank you so much for your great work!

Did you use the "concatenate" operation or "add" operation for the connections that skip the Detection Blocks? I mean the connections which pass the Detection Blocks, not the Mobile DenseNet or the E-MBConv6. I dont' think you mentioned this your the paper.

Thanks in advance!

![SkipConnections](https://user-images.githubusercontent.com/63224740/109559937-9d467900-7adb-11eb-80de-3d913802ee57.png)

**Comment by daniegr** [comment]
@AIGR-sw: Thank you for your interest in our research. To clarify, the mentioned operator for merging the cross-resolutional features and the features of the preceding detection pass is indeed a concatenation. This ensures merging is feasible across different number of feature maps, while maintaining the cross-resolutional features.

**Comment by AIGR-sw** [comment]
@daniegr: Thank you for your answer!

Did you concatenate the cross-resolution features with the Detection Block output (3C feature maps) or with the lower-dimensional confidence map / PAF (after the 1x1 convolution prediction pass)?

**Comment by daniegr** [comment]
@AIGR-sw: The features themselves are forwarded to the next detection block, not the predicted part affinity fields or confidence maps.
