### ISSUE TITLE
FYI: Ported EfficientPose to TFJS with full JavaScript implementation

### ISSUE THREAD

**Issue by vladmandic** [daniegr/EfficientPose#27]
In case anybody is interested, `EfficientPose` works like a charm in TensorFlow/JS and NodeJS  

Converted models, full JS code as well as conversion notes are at:  
<https://github.com/vladmandic/efficientpose>

Tested with variations II-Lite, IV and IV quantized to float16  
(models are included in git repository)  

I've re-implemented decoding using native TFJS ops to squeeze a bit more performance  
(code is fully commented with explanations)  

Thank you for a great model!

**Comment by daniegr** [comment]
@vladmandic: Great work! I have included a reference to your GitHub in the README file.
