### ISSUE TITLE
Convert output to 3d

### ISSUE THREAD

**Issue by missphyrgames** [daniegr/EfficientPose#29]
Hello,

I was wondering how you can convert the coordinate output and convert it into 3d coordinates? I wanted to load the data into for example an fbx file to use on a 3d model.

Thanks!

**Comment by daniegr** [comment]
@missphyrgames: The EfficientPose framework is targeted towards single-person pose estimation from conventional RGB images, and hence provides 2D coordinate estimates. For 3D estimates, I would recommend you either to adjust and fine-tune the EfficientPose models on a 3D/RGB-D dataset of your choice or to utilize a methodology specifically targeting 3D pose estimation.
