### ISSUE TITLE
Model Architecture

### ISSUE THREAD

**Issue by AhmedEssamDakrory** [daniegr/EfficientPose#31]
It is really a great work!
From the title of the paper, I understand that you designed the architecture of the model and trained it to target single person pose estimation; however,  You still use a PAF detection pass as OpenPose which is really important in case of multi person pose estimation. So what will happen if we removed the PAF detection pass ?   Is this pass really important for better accuracy?

**Comment by daniegr** [comment]
@AhmedEssamDakrory: Thank you a lot for the comment and the interesting question! In Appendix A of the [published paper](https://link.springer.com/article/10.1007/s10489-020-01918-7) under "Skeleton estimation" in Table 7 you may observe effect of removing the detection pass performing skeleton estimation (i.e., estimation of PAFs) with EfficientPose I and EfficientPose II. By removing this pass, there is a significant loss in PCKh@50.
