### ISSUE TITLE
Loss in pass 

### ISSUE THREAD

**Issue by mazen930** [daniegr/EfficientPose#32]
How we can calculate the loss on first two passes as they out is 40 but we can only train on 16 as the last pass  and why the input to second and third pass is 160 although the out of previous pass is 40

**Comment by daniegr** [comment]
@mazen930: To do intermediate supervision you need to insert 1x1 convolutions at the end of detection pass 1 and 2. 

Regarding the number of input channels to detection pass 2 and 3, it is a result of the features of the previous pass being concatenated with the cross-resolution features.
