### ISSUE TITLE
Training on MPII 

### ISSUE THREAD

**Issue by AhmedEssamDakrory** [daniegr/EfficientPose#34]
when training on MPII dataset, the images that contain multi persons, did you crop each single person and train on each person separately ?

**Comment by daniegr** [comment]
@AhmedEssamDakrory: That's about it! In accordance with the single-person HPE challenge om MPII, we first utilized the IDs of sufficiently separated individuals to extract single-person instances from the MPII images and cropped the images by using the rough human position and person scale (http://human-pose.mpi-inf.mpg.de/#download) in a similar manner to https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/master/lib/dataset/mpii.py

**Comment by AhmedEssamDakrory** [comment]
Thank you so much for being helpful , I  tried to write a code to crop individual persons from image, using the scale and the rough position of the person, I applied affine transformation (translation followed by scaling)  on the bounding box of the person, but as some bounding boxes of persons do not fit entirely inside the image; some cropped images have black areas on the sides (please have a look at the attached images for more understanding).
Is this acceptable or these black areas will affect the accuracy of the model and I should do further processing to eliminate them and preserve the true joints positions. 
![sd](https://user-images.githubusercontent.com/34447023/115147039-66abca00-a059-11eb-92aa-c61580bf8428.PNG)
![dd](https://user-images.githubusercontent.com/34447023/115147422-2fd6b380-a05b-11eb-9353-1767c98bdfa5.PNG)

**Comment by daniegr** [comment]
@AhmedEssamDakrory: This is similar to what we have experienced, and I consider your solution to be the appropriate way to handle this issue to ensure persons are approximately in the center of the generated images.
