### ISSUE TITLE
Poor accuracy

### ISSUE THREAD

**Issue by kulkarniniraj** [daniegr/EfficientPose#37]
Hi, I am trying to run model over images extracted from single video. All images are single person, front view, 1280x720, png files. 

I ran inference using models i, ii, iii, iv and tf, tflite, torch frameworks. All of them gave consistently poor results on all images. Is there any preprocessing step I am missing?

Here is my command:
`python track.py -p 001.png -v -m iii -f torch`

**Comment by daniegr** [comment]
@kulkarniniraj: I am sorry to hear about the issues you are experiencing. Would you mind sharing some of your sample images and associated predictions?

**Comment by kulkarniniraj** [comment]
The sample image in utils folder works fine. I even tried converting png to jpg, but I haven't seen any improvement. Can image size cause such an issue?

**Comment by daniegr** [comment]
@kulkarniniraj: Image resolution should not matter. However, it could be of importance that the person sufficiently covers the camera view. Shifting from horizontal (i.e., landscape) view to vertical view may be recommended when possible.

**Comment by kulkarniniraj** [comment]
For anybody else who may stumble on this issue, once I cropped out unnecessary background and made sure that person is occupying most of the frame, I got fantastic results.
