### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by A7777-gp** [daniegr/EfficientPose#38]
Thank you for a wonderful job！I have two questions as follows：
1. As a beginner, how can I write such beautiful code like you?
2. I see that your code is based on the pre-training model. How do I train my weight？Do you have the code for this?
Thanks!!!

**Comment by daniegr** [comment]
@A7777-gp: Nice to get to know about your interest in this work. Regarding training of EfficientPose models you may get inspiration from here: #23
