### ISSUE TITLE
Failed on Keras Framework 

### ISSUE THREAD

**Issue by Phantom1003** [daniegr/EfficientPose#39]
During loading the model, it gets a error:
I have tried both tensorflow 2.4.1 and 2.5.0 with python 3.8
```
ValueError: bad marshal data (unknown type code)
```

**Comment by daniegr** [comment]
@Phantom1003: Unfortunately, I am not able to reproduce your error, but for now I will recommend you to adhere to Python 3.6. Please report back to me if the error persists.
