### ISSUE TITLE
Could you share your training code? I want to train the model with my own datasets.

### ISSUE THREAD

**Issue by zhangshaojie1993** [daniegr/EfficientPose#42]

**Comment by daniegr** [comment]
@zhangshaojie1993: Thank you for your interest in EfficientPose! Unfortunately, we are not releasing training code at the moment. However, most details should be covered by our [paper](https://link.springer.com/article/10.1007/s10489-020-01918-7), and also please have a look at previous issues for inspiration, such as this one: #23. Feel free to contact me again if you have further inquiries.
