### ISSUE TITLE
skeleton ?

### ISSUE THREAD

**Issue by RoastedKernel** [daniegr/EfficientPose#43]
is it possible to get the skeleton ? so just the pose without the video content

**Comment by daniegr** [comment]
@RoastedKernel: If you are interested in video inference and you would like only to visualize the predicted skeletons on a black background, I would recommend you to modify line 390 of annotate_video in track.py to the following:

`image = Image.fromarray(np.zeros(frame.shape, dtype=frame.dtype))`

**Comment by RoastedKernel** [comment]
yup thanks solved.
