### ISSUE TITLE
Cannot load Keras model in Tensorflow 2.7

### ISSUE THREAD

**Issue by AndreyRub** [daniegr/EfficientPose#48]
I am trying to load Keras EfficientPose model (https://github.com/daniegr/EfficientPose/blob/master/models/keras/EfficientPoseII.h5)
using the following code:

```
def load_efficient_pose_model():
    custom_objects = {'BilinearWeights': keras_BilinearWeights, 'Swish': Swish(eswish), 'eswish': eswish, 'swish1': swish1}
    model = keras.models.load_model('my_location/EfficientPoseII.h5',custom_objects=custom_objects)
When using Tensorflow 1.13.1 and Keras, everything works correctly. However, when I am using Tensorflow 2.7 (with built-in Keras), the following mistake happens:
```

Traceback (most recent call last):
```
   ....
  File "/home/ubuntu/anaconda3/envs/tf2_runtime/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/daniegr/Programming/EfficientPose/utils/units.py", line 90, in <lambda>
NameError: name 'K' is not defined
```
I've also tried loading the model in Tensorflow 1.13.1 and saving model and weights separetly, but the problem remains.

When serializing the model to JSON, I am getting these interesting lines:

```
        {
            "name": "lambda_1_res1",
            "class_name": "Lambda",
            "config": {
                "name": "lambda_1_res1",
                "trainable": false,
                "function": [
                    "4wEAAAAAAAAAAQAAAAEAAABTAAAAcwQAAAB8AFMAKQFOqQApAdoBeHIBAAAAcgEAAAB6Ri9Vc2Vy\ncy9kYW5pZWdyL1Byb2dyYW1taW5nL0VmZmljaWVudFBvc2UvbW9kZWxzL2VmZmljaWVudG5ldHMv\nbW9kZWwucHnaCDxsYW1iZGE+HQEAAPMAAAAA\n",
                    null,
                    null
                ],
                "function_type": "lambda",
                "output_shape": null,
                "output_shape_type": "raw",
                "arguments": {}
            },
```
My guess is that somehow the old model saves parts of code which access K as backend, which is not available in Tensorflow 2.
Any idea?

**Comment by daniegr** [comment]
@AndreyRub: Thank you for reporting this issue! I must admit that I have not tested the framework in TF 2.7 yet since its release earlier this month. I would therefore for now recommend to stick with TF 2.5.2. However, if you should identify your issue with TF 2.7, I would be glad if you informed me about it. Cheers

**Comment by AndreyRub** [comment]
Thanks for your prompt response. I will try again with TF2.5.2 and report back

**Comment by AndreyRub** [comment]
I've tested with TF2.5.2 and I can confirm that it works. The issue is related to TF2.7
