### ISSUE TITLE
EfficientNet Backbones

### ISSUE THREAD

**Issue by 1Nokta** [daniegr/EfficientPose#50]
Did I understand correctly that you have pre-trained the Efficientnet backbones yourself? The backbones with the MBConv variations you introduced do not resemble those of the original Efficientnet family, right?

**Comment by daniegr** [comment]
@1Nokta: Thank you for your interest in our research. For the ImageNet pretrained blocks of EfficientNet and EfficientNet Lite backbones in EfficientPose and EfficientPose Lite, respectively, we have turned to the implementations by [https://github.com/qubvel/efficientnet](Pavel Yakubovskiy) and [https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet](TensorFlow).
