### ISSUE TITLE
Good start (for me)

### ISSUE THREAD

**Issue by neilyoung** [daniegr/EfficientPose#54]
At first - congratulations. This is more or less the very first AI project, which did run OOB :)

I'm looking for a way to derive the camera pose (translation and rotation in world coordinates) from the human pose detected, like OpenCV solvePnP. Would that be possible somehow?

**Comment by neilyoung** [comment]
Specifying "keras" as framework is initially accepted, but fails in "units.py", line 90 with "name "K" is not defined"

**Comment by daniegr** [comment]
@neilyoung: Thank you for reporting this issue. Could you please provide some details about your environment for me to replicate this scenario?

**Comment by neilyoung** [comment]
Well, nothing fancy. It is a Gigabyte 5 laptop with Nvidia RX3060, running Ubuntu 20.04. Your code is run in a conda environment.
