### ISSUE TITLE
Can it be developed to track multiple people' pose

### ISSUE THREAD

**Issue by neverwinterguyVN** [daniegr/EfficientPose#8]
Do you have a plan for it

**Comment by daniegr** [comment]
@neverwinterguyVN The EfficientPose framework is mainly targeted towards high-precision pose estimation of single instances, but the framework can indeed be extended to support multi-person pose estimation in several ways: 1) The part affinity fields incorporated into the models may be utilized to distinguish between multiple people by providing traits about skeleton configurations. The models may require retraining on multi-person datasets such as MPII or COCO to perform this task with high precision. 2) The framework can be extended with a separate stage for object detection, to first detect the respective persons in a multiple person video, and then perform single-person pose estimation with EfficientPose on the proposed bounding boxes subsequently. Good luck with your investigation!
